spring:
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 10MB

server:
  port: 8090
  context-path: /springboot
  tomcat:
    uri-encoding: UTF-8
  session-timeout: 5000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript

mybatis:
  config: classpath:config/mybatis/mybatis-config.xml
  mapperLocations: classpath:config/mybatis/mapper/**/*.xml
  typeAliasesPackage: com.feifan.web.model
  checkConfigLocation: true

datasource:
  cms: aa

---
spring:
  profiles: pro
  redis:
    host: 10.111.70.51
    port: 7379
    password: test
    timeout: 100000
    database: 1
    pool:
      max-active: 300
      max-idle: 100
      max-wait: 1000
      min-idle: 10
  http:
    multipart:
      max-file-size: 10MB
