spring:
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 10MB

server:
  port: 8090
  context-path: /springboot
  tomcat:
    uri-encoding: UTF-8
  session-timeout: 5000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript

mybatis:
  config: classpath:mybatis/mybatis-config.xml
  mapperLocations: classpath:mybatis/mapper/**/*.xml
  typeAliasesPackage: com.feifan.web.model
  checkConfigLocation: true

datasource:
  bike:
    driverClassName: xxx
    url: xxx
    username: xxx
    password: xxx
    jmxEnabled: false
    testWhileIdle: false
    validationQuery: SELECT 1
    testOnBorrow: true
    testOnReturn: false
    validationInterval: 30000
    timeBetweenEvictionRunsMillis: 10000
    maxActive: 5
    maxIdle: 2
    minIdle: 1
    initialSize: 2
    maxWait: 60000
    removeAbandoned: true
    removeAbandonedTimeout: 60000
    minEvictableIdleTimeMillis: 60000
    logAbandoned: true
    cryptographic: false

